### ISSUE TITLE
Todo: update API based on Castor API updates

### ISSUE THREAD

**Issue by wouterpotters** [wouterpotters/castor-python#9]
The castor API was updated three times. Need to update this package to reflect those changes:

**Castor EDC Release 2021.4**

- [ ] Added ability to filter report instances by archived parameter. Return only unarchived report instances by default.
- [ ] Added create Institute API endpoint (POST /study/{studyId}/institute).

**Castor EDC Release 2021.3**
- [ ] Added Randomization API endpoint (/study/{studyId}/record/{recordId}/randomization) with support for GET to read a record's randomization details and POST to randomize a record.

**Castor EDC Release 2021.2**
- [x] Locking a survey package instance is now possible when Edit OR Lock permissions are set. Support for Edit permissions is deprecated and will be removed in a future release.
- [x] Survey Data permissions are now needed to read a survey package instance survey_url_string. 'Hidden' will be shown when permissions are insufficient.
- [ ] Added ability to filter survey package instances by finished_on parameter.
- [ ] Add optional field[FIELD_ID]=FIELD_VALUE parameters on GET /record endpoint to filter records by field value.
- [ ] Added archived property to the report instance resource.
- [x] Fixed errors when trying to load survey package instances for a single record (2021.2.3)
- [ ] Added randomized_on property in Record endpoint for users with RandomizationRead or RandomizationWrite permission.

**Comment by wouterpotters** [comment]
no further updates planned. Close issue
